[package]
name = "libp2p-gossipsub"
version = "0.1.0"
authors = ["James Ray (@jamesray1)"]

[dependencies]
libp2p_floodsub = { path = "../floodsub"}
libp2p_kad = { path = "../kad"}
libp2p_core = { path = "../core"}
time = "0.1"
